name: Node.js CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm 

      - name: Install Dependencies
        run: npm install

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nodejs-artifact
          path: dist/